ad.ui.lang=en
ad.invite.created_list_encrypted=00
ad.invite.received_list_encrypted=00
ad.security.invitation_permissions=00
ad.roster.favorites=
ad.roster.items=
ad.msg.data=version=3;;104,,,0,0,00,00,0,0,0,00,1723464484945093,0,0,0,0,0,0,
ad.msg.channels_states=
